
# GET  http://localhost:3000 HTTP/1.1

# GET  http://localhost:3000/user/1 HTTP/1.1

# POST http://localhost:3000/create HTTP/1.1
# Content-Type: application/json

# {
#   "name": "ferhannah",
#   "email": "666666666@66.com"
# }

# GET  http://localhost:3000/user/index?a=333 HTTP/1.1

POST   http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
  // "name": "f3",
  "email": "222@22.com"
}